name: fund-monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '30 10 * * 1-5'   # UTC 10:30（东京19:30）

jobs:
  run-review:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run fund review (nav/estimate only)
        env:
          SCT_KEY: ${{ secrets.SCT_KEY }}
          TOTAL_ASSETS: ${{ secrets.TOTAL_ASSETS }}
        run: |
          echo "Fund-only review at $(date -u '+%F %T') UTC"
          # 复用同一份逻辑，脚本内部会区分 FUND/ETF；这里运行一次即可
          python check_once.py
