name: intraday-check

on:
  workflow_dispatch:
  schedule:
    # 例：周一至周五，UTC 0:10~7:10 每小时触发一次；你已有 2min×30 的循环，够用了
    - cron: "10 0-7 * * 1-5"

jobs:
  run-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      # 三层兜底：Secrets > Variables > 默认
      TOTAL_ASSETS: ${{ secrets.TOTAL_ASSETS != '' && secrets.TOTAL_ASSETS || vars.TOTAL_ASSETS != '' && vars.TOTAL_ASSETS || '100000' }}
      POSITION_PCT: ${{ vars.POSITION_PCT != '' && vars.POSITION_PCT || '0.10' }}   # 总资产里，用于“进攻仓”上限
      ATTACK_PCT:   ${{ vars.ATTACK_PCT   != '' && vars.ATTACK_PCT   || '0.035' }}  # 单笔 3.5%（你设 3~4%）
      SCKEY:        ${{ secrets.SCKEY }}  # Server酱，可为空

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Intraday loop (2min × 30)
        run: |
          echo "Start intraday loop at: $(date -u '+%F %T') UTC"
          for i in $(seq 1 30); do
            echo "== iteration ${i} =="
            python check_once.py || true
            sleep 120
          done
