name: intraday-check

on:
  workflow_dispatch:
  schedule:
    # 交易日早盘前触发（UTC，周一~周五）
    - cron: '28 1 * * 1-5'
    # 午盘前触发
    - cron: '58 4 * * 1-5'

jobs:
  run-check:
    runs-on: ubuntu-latest
    timeout-minutes: 70

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Intraday loop (2min × 30)
        env:
          SCT_KEY: ${{ secrets.SCT_KEY }}
          TOTAL_ASSETS: ${{ secrets.TOTAL_ASSETS }}
        run: |
          echo "Start intraday loop at: $(date -u '+%F %T') UTC"
          for i in $(seq 1 30); do
            echo "== iteration $i =="
            python check_once.py
            sleep 120
          done
