name: nightly-review

on:
  schedule:
    # 每个交易日「东京 21:30 / 北京 20:30」运行；如要稳妥晚一点可改 13:30→14:30
    - cron: "30 12 * * 1-5"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install requests

      # 1) 抓取官方净值/收盘价 -> reports/nav/YYYY-MM-DD.csv（必产物，失败行标记 fetch_error）
      - name: Fetch NAV & closes
        run: python nav_fetch.py

      # 2) 生成日报（会自动把当日 signals.csv + nav/当日.csv 合并展示，并通过 Server酱推送摘要）
      - name: Build daily review
        env:
          SERVER_CHAN_KEY: ${{ secrets.SERVER_CHAN_KEY }}
        run: python daily_review.py

      # 3) 提交变更：只在目录存在且有改动时提交，避免 pathspec 报错
      - name: Commit reports if changed
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 分目录 add（存在才 add）
          [ -d reports/nav ]   && git add -A reports/nav
          [ -d reports/daily ] && git add -A reports/daily
          [ -d logs ]          && git add -A logs

          # 没有 staged 变更就不提交
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "nightly review: $(date -u +%F)"
            git push
          fi
