name: nightly-suite

on:
  workflow_dispatch:
  schedule:
    # 东京时间 20:05 运行（UTC 要 -9h）
    - cron: "5 11 * * *"

permissions:
  contents: write
  pull-requests: write

env:
  TZ: Asia/Tokyo
  PYTHONUNBUFFERED: "1"

jobs:
  fetch-and-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Create venv & install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run nightly nav fetch + review
        id: run_fetch
        run: |
          . .venv/bin/activate
          echo "Start nav_fetch at $(date -u '+%F %T') UTC"
          .venv/bin/python nav_fetch.py
          echo "Done nav_fetch at $(date -u '+%F %T') UTC"

      # （可选）上传生成的 csv/md 工件，供 Actions 页面下载
      - name: Upload artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "reports-${{ github.run_id }}"
          path: |
            reports/nav/**/*.csv
            reports/daily/**/*.md
          if-no-files-found: ignore
          compression-level: 6

      # 生成 PR 分支并提交
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "bot/nightly-${{ github.run_id }}"
          base: "main"
          title: "nightly: NAV ${{ env.TZ }} $(date +'%Y-%m-%d') & review"
          body: "This PR contains the nightly NAV data and review."
          signoff: false
          delete-branch: true

      # 自动合并（如你仓库策略允许）。没有变更时此步会自然跳过。
      - name: Enable PR Auto-merge (squash)
        if: steps.cpr.outputs.pull-request-number != ''
        run: |
          gh pr merge "${{ steps.cpr.outputs.pull-request-number }}" --squash --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
