name: nightly-suite

on:
  workflow_dispatch:
  schedule:
    # 每天 21:00 UTC 触发（北京时间 +8 = 次日 05:00；东京 +9 = 次日 06:00）
    - cron: "0 21 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch-and-review:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests pandas pytz

      - name: Run NAV fetch
        run: |
          python nav_fetch.py

      - name: Build daily review
        run: |
          python daily_review.py

      - name: Detect changes
        id: detect
        run: |
          git status --porcelain
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true"  >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes (if any)
        if: steps.detect.outputs.changed == 'true'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "nightly: NAV $(date -u +'%Y-%m-%d') & review $(date -u +'%Y-%m-%d')" || true

      - name: Create Pull Request
        if: steps.detect.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "nightly review ${{ github.run_id }}"
          body: |
            This PR contains nightly NAV data and review.
            NAV date: $(date -u +'%Y-%m-%d')
          branch: "bot/nightly-${{ github.run_id }}"
          commit-message: "nightly: update NAV & daily review"
          delete-branch: true
          labels: automated, nightly

      - name: Enable PR Auto-merge (squash)
        if: steps.detect.outputs.changed == 'true'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash

      - name: Collect artifacts
        run: |
          mkdir -p artifacts
          if [ -d "reports" ]; then tar -czf artifacts/reports_$(date -u +%Y%m%d).tgz reports; fi
          if [ -d "logs" ];    then tar -czf artifacts/logs_$(date -u +%Y%m%d).tgz    logs;    fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nightly-artifacts-${{ github.run_id }}
          path: artifacts
          if-no-files-found: ignore
