name: nightly-suite

on:
  workflow_dispatch:
  schedule:
    # 东京时间 20:05（UTC 11:05）
    - cron: "5 11 * * *"

permissions:
  contents: write
  pull-requests: write

env:
  TZ: Asia/Tokyo
  PYTHONUNBUFFERED: "1"

jobs:
  fetch-and-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create venv & install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run nightly nav fetch + review
        id: run_fetch
        run: |
          . .venv/bin/activate
          echo "Start nav_fetch at $(date -u '+%F %T') UTC"
          .venv/bin/python nav_fetch.py
          echo "Done nav_fetch at $(date -u '+%F %T') UTC"

      - name: Upload artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "reports-${{ github.run_id }}"
          path: |
            reports/nav/**/*.csv
            reports/daily/**/*.md
          if-no-files-found: ignore
          compression-level: 6

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "bot/nightly-${{ github.run_id }}"
          base: "main"
          title: "nightly: NAV ${{ env.TZ }} $(date +'%Y-%m-%d') & review"
          body: "This PR contains the nightly NAV data and review."
          signoff: false
          delete-branch: true

      - name: Enable PR Auto-merge (squash)
        if: steps.cpr.outputs.pull-request-number != ''
        run: |
          gh pr merge "${{ steps.cpr.outputs.pull-request-number }}" --squash --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
