name: nightly-review

on:
  schedule:
    - cron: "0 13 * * *" # UTC 13:00 = Asia/Tokyo 22:00，每天晚上10点跑
  workflow_dispatch:      # 手动触发

jobs:
  fetch-nav-and-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Fetch NAV
        run: |
          python scripts/fetch_nav.py

      - name: Build daily review
        run: |
          python scripts/daily_review.py

      - name: Commit changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add reports/nav || true
          git add reports/daily || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "nightly review: $(date -u +%F)"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: nightly review: ${{ github.run_id }}
          title: "Nightly review ${{ github.run_id }}"
          body: |
            This PR contains the nightly NAV data and review for $(date -u +%F).
          branch: "auto/nightly-review"
          base: main
          delete-branch: true
