name: nightly-suite

on:
  workflow_dispatch:   # 手动触发
  schedule:
    - cron: "0 21 * * *"  # 每天 UTC 21 点触发 (北京时间 05:00)

jobs:
  fetch-and-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install requests pandas

      - name: Run nightly nav fetch + review
        run: python nav_fetch.py

      - name: Upload intraday quotes (optional)
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: intraday-quotes
          path: quotes/*.csv

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update nightly nav data"
          branch: "auto/nightly-nav"
          title: "Nightly NAV Update"
          body: "This PR contains the latest NAV data from nightly run."
          delete-branch: true

      - name: Enable PR Auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
