name: nightly-suite

on:
  workflow_dispatch:
  schedule:
    # UTC 13:30 运行；东京+9 相当于 22:30。按需修改。
    - cron: "30 13 * * *"

jobs:
  fetch-and-review:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # 推送、建分支
      pull-requests: write   # 建 PR、开自动合并

    env:
      # 给日报标题用的日期，代码里也可自己算；这里先占位
      NAV_DATE: ${{ vars.NAV_DATE || '' }}
      REVIEW_DATE: ${{ vars.REVIEW_DATE || '' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run nightly nav fetch + review
        run: |
          python nav_fetch.py
          python daily_review.py

      # 可选：把当日盘中快照作为构件上传（文件名已避免冒号）
      - name: Upload intraday quotes (optional)
        uses: actions/upload-artifact@v4
        with:
          name: quotes
          path: quotes/*.csv
          if-no-files-found: ignore

      # 只创建 PR（注意：不要在这里传 auto-merge/merge-method）
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            reports/nav/*.csv
            reports/daily/*.md
          branch: bot/nightly-${{ github.run_id }}
          title: "nightly: NAV ${{ env.NAV_DATE }} & review ${{ env.REVIEW_DATE }}"
          body:  "Auto generated by nightly-suite"
          commit-message: "nightly: NAV & review"
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}

      # 启用自动合并（squash）
      - name: Enable PR Auto-merge (squash)
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
