name: nightly-review

on:
  schedule:
    # UTC 12:30 = 北京 20:30 / 东京 21:30
    - cron: "30 12 * * 1-5"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: nightly-review
  cancel-in-progress: true

jobs:
  run-nightly:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install requests

      # 1) 抓净值/收盘价 → reports/nav/YYYY-MM-DD.csv
      - name: Fetch NAV & closes
        run: |
          python nav_fetch.py
          echo "---- after nav_fetch.py ----"
          ls -lah reports || true
          ls -lah reports/nav || true

      # 2) 生成日报 → reports/daily/YYYY-MM-DD.md
      - name: Build daily review
        env:
          SERVER_CHAN_KEY: ${{ secrets.SERVER_CHAN_KEY }}
        run: |
          python daily_review.py
          echo "---- after daily_review.py ----"
          ls -lah reports/daily || true

      # 3) 计算日期 & PR 分支名（供后面引用）
      - name: Compute meta
        id: meta
        shell: bash
        run: |
          d=$(date -u +%F)
          echo "date=$d"   >> $GITHUB_OUTPUT
          echo "branch=bot/nightly-$d" >> $GITHUB_OUTPUT

      # 4) 创建 PR（不会直接 push 到 main；无变更自动跳过）
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "nightly review: ${{ steps.meta.outputs.date }}"
          title: "nightly review ${{ steps.meta.outputs.date }}"
          body: |
            Auto-generated nightly review.
            - NAV snapshot: reports/nav/${{ steps.meta.outputs.date }}.csv
            - Daily report: reports/daily/${{ steps.meta.outputs.date }}.md
          branch: ${{ steps.meta.outputs.branch }}
          base: main
          delete-branch: true
          add-paths: |
            reports/**
            logs/**
